### PR TITLE
Do not crash if runtime is absent

### LINKED ISSUE #1181: NoSuchElementException in ZiplineApis.rewritePair
This crash is triggered when the Zipline Gradle plugin is applied but there’s no Zipline classes on the classpath. We should just add those classes automatically so you can’t get it wrong.

```
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at app.cash.zipline.kotlin.ZiplineApis.rewritePair(ZiplineApis.kt:298)
	at app.cash.zipline.kotlin.ZiplineApis.<init>(ZiplineApis.kt:196)
	at app.cash.zipline.kotlin.ZiplineIrGenerationExtension.generate(ZiplineIrGenerationExtension.kt:36)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda$1(JvmIrCodegenFactory.kt:225)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:107)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:255)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:59)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.convertToIr(KotlinToJVMBytecodeCompiler.kt:224)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
```

### PR DESCRIPTION
**Pull request by JakeWharton**
This is useful to allow targets we don't yet support, or when applying only to test code and not main code.

Closes #1181

### CODE REVIEW

File: zipline-kotlin-plugin/src/main/kotlin/app/cash/zipline/kotlin/ZiplineApis.kt [hunk 1]
```diff
@@ -192,14 +192,16 @@ internal class ZiplineApis(
...
   /** Keys are renderings of functions like `Zipline.take()` and values are their rewrite targets. */
-  val ziplineServiceAdapterFunctions: Map<String, IrSimpleFunctionSymbol> = listOf(
-    rewritePair(ziplineClassId.callableId("take")),
-    rewritePair(endpointClassId.callableId("take")),
-    rewritePair(ziplineClassId.callableId("bind")),
-    rewritePair(endpointClassId.callableId("bind")),
-    rewritePair(ziplineServiceAdapterFunctionCallableId),
-    rewritePair(ziplineServiceSerializerFunctionCallableId),
-  ).toMap()
+  val ziplineServiceAdapterFunctions: Map<String, IrSimpleFunctionSymbol> by lazy {
```
Comment (swankjesse) [inline zipline-kotlin-plugin/src/main/kotlin/app/cash/zipline/kotlin/ZiplineApis.kt]: 👍🏻

**Review by swankjesse — APPROVED** [review]

File: zipline-gradle-plugin/src/test/projects/no-runtime/lib/build.gradle.kts [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+import app.cash.zipline.gradle.ZiplineCompileTask
+import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnPlugin
+import org.jetbrains.kotlin.gradle.targets.js.yarn.YarnRootExtension
+
+plugins {
+  kotlin("multiplatform")
+  id("app.cash.zipline")
```
Comment (swankjesse) [inline zipline-gradle-plugin/src/test/projects/no-runtime/lib/build.gradle.kts:22]: Will this add the runtime unconditionally? I don’t know how to be confident that this won’t regress through automatic dependencies, other than perhaps explicitly excluding it

Comment (JakeWharton) [reply zipline-gradle-plugin/src/test/projects/no-runtime/lib/build.gradle.kts:22]: The plugin does not add the runtime today. This test would continue to pass if it did, though. I can add an assertion against that.

Comment (JakeWharton) [reply zipline-gradle-plugin/src/test/projects/no-runtime/lib/build.gradle.kts:22]: Huh I added a test for that and something unrelated failed, so I'll be fixing two things!

Comment (JakeWharton) [reply zipline-gradle-plugin/src/test/projects/no-runtime/lib/build.gradle.kts:22]: Done
