### PR TITLE
Compile JVM JNI native libaries using Zig, add Linux ARM

### LINKED ISSUE #1479: Requesting support for Linux ARM
I am trying to build on Linux ARM machine but getting this error

`Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: Unable to read /jni/aarch64/libquickjs.so from JAR [in thread "DefaultDispatcher-worker-1"]
                at app.cash.zipline.QuickJsNativeLoaderKt.loadNativeLibrary(QuickJsNativeLoader.kt:36)
                at app.cash.zipline.QuickJs.<clinit>(QuickJs.kt:36)
                ... 9 more
        Suppressed: java.lang.NoClassDefFoundError: Could not initialize class app.cash.zipline.QuickJs
                ... 9 more`

| Header | Header |
|--------|--------|
| Image | Image |

On further deep diving found out that from the zipline implementation that ARM is not supported and it’s building only for linux amd 64.
https://github.com/cashapp/zipline/blob/b32e6ec85735341e3a4b0522631b93edcd11fe29/.github/workflows/release.yaml

**Requesting support for Linux ARM**

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #1479. Closes #421.

### CODE REVIEW

**Review by squarejesse — APPROVED** [review]

File: zipline/native/include/LICENSE [hunk 1]
```diff
@@ -0,0 +1,347 @@
...
+    Ty Coon, President of Vice
+
+This General Public License does not permit incorporating your program into
+proprietary programs.  If your program is a subroutine library, you may
+consider it more useful to permit linking proprietary applications with the
+library.  If this is what you want to do, use the GNU Library General Public
+License instead of this License.
+
+
+"CLASSPATH" EXCEPTION TO THE GPL
```
Comment (squarejesse) [inline zipline/native/include/LICENSE:326]: This part’s important! And hiding

File: zipline/build.zig [hunk 2]
```diff
@@ -0,0 +1,95 @@
+const std = @import("std");
+
+pub fn build(b: *std.Build) !void {
+  // The Windows builds create a .lib file in the lib/ directory which we don't need.
+  const deleteLib = b.addRemoveDirTree(b.getInstallPath(.prefix, "lib"));
+  b.getInstallStep().dependOn(&deleteLib.step);
```
Comment (JakeWharton) [inline zipline/build.zig:6]: We don't do Windows at the moment, but might in the future (https://github.com/cashapp/zipline/issues/1360). It should be easier now, anyway.

**Comment by JakeWharton** [comment]
Once it goes green I will change the required status checks and then merge.
