### PR TITLE
Show available functions on unexpected function

### LINKED ISSUE #402: Throw the right exceptions with useful information
It's hard to know what's going on in zipline when an API changes. We should throw the correct `NoSuchMethodError` if nothing can be resolved properly. 

```
NoSuchMethodError:
  invoked:
    ZiplineTreehouse.getScreen(String): ZiplineReference<ZiplineTreehouseUi>
  candidates:
    ZiplineTreehouse.getScreen(String, Navigator): ZiplineReference<ZiplineTreehouseUi>
    ZiplineTreehouse.doTheThing(String, Navigator): ZiplineReference<ZiplineTreehouseUi>
    ZiplineTreehouse.close(): ZiplineReference<ZiplineTreehouseUi>

```

### PR DESCRIPTION
**Pull request by veyndan**
Closes #402.

### CODE REVIEW

File: zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/inbound.kt [hunk 1]
```diff
@@ -89,7 +90,16 @@ internal class InboundCall(
...
 
-  fun unexpectedFunction(): Array<String> = error("unexpected function: $funName")
+  fun unexpectedFunction(supportedFunctionNames: List<String>): Array<String> = throw ZiplineApiMismatchException(
+    buildString {
+      appendLine("no such method (incompatible API versions?)")
+      appendLine("\tcalled:")
+      append("\t\t")
+      appendLine(funName)
+      appendLine("\tavailable:")
+      append(supportedFunctionNames.joinToString(separator = "\n") { "\t\t$it" })
```
Comment (JakeWharton) [inline zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/inbound.kt]:
```suggestion
      supportedFunctionNames.joinTo(this, separator = "\n") { "\t\t$it" }
```

**Review by JakeWharton — APPROVED** [review]

**Review by swankjesse — APPROVED** [review]
