### PR TITLE
Fix UTF-8 encoding of inputs and outputs

### LINKED ISSUE #214: Emoji roundtrip fails

### PR DESCRIPTION
**Pull request by swankjesse**
Use the Java APIs rather than the JNI APIs to convert char* to UTF-8
and back. The Java APIs use UTF-8, not modified UTF-8.

Also include a trailing '\u0000', which QuickJS expects (even though
it accepts the string length as a parameter).

Also fix a bug where the test case had an unexpected unprintable
character.

Closes: https://github.com/cashapp/quickjs-java/issues/214

### CODE REVIEW

File: quickjs/common/test/app/cash/quickjs/QuickJsTest.java [hunk 1]
```diff
@@ -85,9 +84,8 @@
     }
   }
 
-  @Ignore("https://github.com/cashapp/quickjs-java/issues/214")
   @Test public void emojiRoundTrip() {
-    assertThat(quickjs.evaluate("\"\uD83D\uDC1D️\""))
-        .isEqualTo("\uD83D\uDC1D️️");
+    assertThat(quickjs.evaluate("\"a\uD83D\uDC1Dcdefg\""))
+        .isEqualTo("a\uD83D\uDC1Dcdefg");
```
Comment (swankjesse) [inline quickjs/common/test/app/cash/quickjs/QuickJsTest.java:89]: on trunk this fails in two ways. The emoji is encoded wrong, and the remainder of the string is truncated.

```
expected: a🐝cdefg
but was : aðcd
```

**Review by JakeWharton — APPROVED** [review]
