### PR TITLE
Don't access the project in ziplineApiDump

### LINKED ISSUE #1230: ziplineApiDump doesn’t work with the configuration cache
```
> Task ziplineApiDump

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache problems found in this build.

4 problems were found storing the configuration cache, 2 of which seem unique.
- Task `:compileKotlinJvmZiplineApiDump` of type `app.cash.zipline.gradle.ValidateZiplineApiTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
```

### PR DESCRIPTION
**Pull request by swankjesse**
Closes: https://github.com/cashapp/zipline/issues/1230

### CODE REVIEW

File: zipline-gradle-plugin/src/main/kotlin/app/cash/zipline/gradle/ValidateZiplineApiTask.kt [hunk 1]
```diff
@@ -48,6 +47,9 @@ abstract class ValidateZiplineApiTask @Inject constructor(
   @get:OutputFile
   abstract val ziplineApiFile: RegularFileProperty
 
+  @get:Input
+  abstract val projectDirectory: Property<String>
```
Comment (swankjesse) [inline zipline-gradle-plugin/src/main/kotlin/app/cash/zipline/gradle/ValidateZiplineApiTask.kt:51]: String because I care about the directory path, but not its contents

**Comment by swankjesse** [comment]
I was unsuccessful writing a regression test for this.
https://github.com/gradle/gradle/issues/27748

**Review by dellisd — APPROVED** [review]
