### PR TITLE
Change our wrapper exception to ZiplineException

### LINKED ISSUE #676: Default exception type should be ZiplineException
Instead of `Exception`, which is quite ambiguous.

### PR DESCRIPTION
**Pull request by swankjesse**
This should make it easier to catch exceptions thrown
across the ZiplineService boundary.

Closes: https://github.com/cashapp/zipline/issues/676

### CODE REVIEW

File: zipline/src/commonMain/kotlin/app/cash/zipline/ZiplineException.kt [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+ * This is similar to a wrapping exception like Java's `InvocationTargetException`, but the wrapped
+ * exception type is not generally available because its class might not exist in the catching
+ * process.
+ */
+class ZiplineException(
+  message: String?,
+  cause: Throwable?,
+) : RuntimeException(message, cause) {
+  constructor(message: String?) : this(message, null)
+  constructor(cause: Throwable?) : this(null, cause)
```
Comment (JakeWharton) [inline zipline/src/commonMain/kotlin/app/cash/zipline/ZiplineException.kt]: Why this and not primary + default argument values? JNI would have to call the two-arg one with explicit nulls, but you get a nicer Kotlin API.

Also anything accessed through JNI needs listed in the shrinker rules.

**Review by JakeWharton — APPROVED** [review]

File: zipline/src/commonMain/kotlin/app/cash/zipline/ZiplineException.kt (hunk 1 above)
Comment (swankjesse) [reply zipline/src/commonMain/kotlin/app/cash/zipline/ZiplineException.kt]: Just following the old Java conventions like a chump. Lemme do defaults.
