### PR TITLE
Patch for StackOverflow on Recursive Class Definitions.

### LINKED ISSUE #1163: Stack Overflow after 1.2.0, because of shared commit.
Some Traces thrown from plugins are very opaque on the cause of the crash, or am I missing something here ?

```
app.cash.zipline.ZiplineException: CompletionHandlerException: Exception in completion handler InvokeOnCompletion@4[job@5] for DeferredCoroutine{Completed}@5
                                                                                                    	at captureStack (runtime/coreRuntime.kt:12)
                                                                                                    	at CompletionHandlerException (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/Exceptions.common.kt:1813)
                                                                                                    	at notifyCompletion (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/JobSupport.kt:158)
                                                                                                    	at completeStateFinalization (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/JobSupport.kt:325)
                                                                                                    	at finalizeFinishingState (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/JobSupport.kt:236)
                                                                                                    	at tryMakeCompletingSlowPath (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/JobSupport.kt:910)
                                                                                                    	at tryMakeCompleting (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/JobSupport.kt:867)
                                                                                                    	at <anonymous> (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/JobSupport.kt:832)
                                                                                                    	at <anonymous> (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/AbstractCoroutine.kt:99)
                                                                                                    	at <anonymous> (src/kotlin/coroutines_13/CoroutineImpl.kt:45)
                                                                                                    	at <anonymous> (kotlin-kotlin-stdlib-js-ir.js)
                                                                                                    	at <anonymous> (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt:112)
                                                                                                    	at <anonymous> (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/js/src/JSDispatcher.kt:155)
                                                                                                    	at <anonymous> (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/js/src/JSDispatcher.kt)
                                                                                                    	at apply (native)
                                                                                                    	at <anonymous> (runner/work/zipline/zipline/zipline/src/jsMain/kotlin/app/cash/zipline/GlobalBridge.kt:72)
                                                                                                    	at <anonymous> (runner/work/zipline/zipline/zipline/src/commonMain/kotlin/app/cash/zipline/internal/GuestService.kt)
                                                                                                    	at <anonymous> (zipline-root-zipline.js)
                                                                                                    	at <anonymous> (runner/work/zipline/zipline/zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/InboundService.kt:53)
                                                                                                    	at <anonymous> (runner/work/zipline/zipline/zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/Endpoint.kt:99)
                                                                                                    	at <anonymous> (zipline-root-zipline.js)
                                                                                                    	at <anonymous> (runner/work/zipline/zipline/zipline/src/jsMain/kotlin/app/cash/zipline/GlobalBridge.kt)
                                                                                                    	at <anonymous> (zipline-root-zipline.js)
                                                                                                        Suppressed: DiagnosticCoroutineContextException: [DeferredCoroutine{Completed}@5, SetTimeoutDispatcher@3]
                                                                                                    	at captureStack (runtime/coreRuntime.kt:12)
                                                                                                    	at DiagnosticCoroutineContextException (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/js/src/internal/CoroutineExceptionHandlerImpl.kt:8709)
                                                                                                    	at handleUncaughtCoroutineException (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/internal/CoroutineExceptionHandlerImpl.common.kt:46)
                                                                                                    	at handleCoroutineException (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/CoroutineExceptionHandler.kt:32)
                                                                                                    	at <anonymous> (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/AbstractCoroutine.kt:107)
                                                                                                    	at notifyCompletion (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/JobSupport.kt:158)
                                                                                                            ... and 21 more common stack frames skipped
                                                                                                    Caused by:     at captureStack (runtime/coreRuntime.kt:12)
                                                                                                    	at ClassCastException_init_$Create$ (kotlin-kotlin-stdlib-js-ir.js)
                                                                                                    	at THROW_CCE (runtime/hacks.kt)
                                                                                                    	at <anonymous> (soundbound-extensions-lib.js)
                                                                                                    	at <anonymous> (opt/buildAgent/work/b2fef8360e1bcf3d/formats/json/commonMain/src/kotlinx/serialization/json/internal/Polymorphic.kt:20)
                                                                                                    	at <anonymous> (opt/buildAgent/work/b2fef8360e1bcf3d/core/commonMain/src/kotlinx/serialization/encoding/AbstractEncoder.kt:80)
                                                                                                    	at <anonymous> (opt/buildAgent/work/b2fef8360e1bcf3d/core/commonMain/src/kotlinx/serialization/internal/CollectionSerializers.kt:68)
                                                                                                    	at <anonymous> (kotlinx-serialization-kotlinx-serialization-core.js)
                                                                                                    	at <anonymous> (opt/buildAgent/work/b2fef8360e1bcf3d/formats/json/commonMain/src/kotlinx/serialization/json/internal/Polymorphic.kt:20)
2023-11-07 23:30:07.725   813-891   Zipline                 in.shabinder.soundbound.preview      E  	at <anonymous> (opt/buildAgent/work/b2fef8360e1bcf3d/core/commonMain/src/kotlinx/serialization/encoding/AbstractEncoder.kt:80)
                                                                                                    	at <anonymous> (commonMainSources/libraries/stdlib/src/kotlin/util/Preconditions.kt:1876)
                                                                                                    	at <anonymous> (zipline-root-zipline.js)
                                                                                                    	at <anonymous> (opt/buildAgent/work/b2fef8360e1bcf3d/formats/json/commonMain/src/kotlinx/serialization/json/internal/Polymorphic.kt:20)
                                                                                                    	at <anonymous> (opt/buildAgent/work/b2fef8360e1bcf3d/core/commonMain/src/kotlinx/serialization/encoding/AbstractEncoder.kt:80)
                                                                                                    	at <anonymous> (opt/buildAgent/work/b2fef8360e1bcf3d/core/commonMain/src/kotlinx/serialization/encoding/Encoding.kt:92)
                                                                                                    	at <anonymous> (zipline-root-zipline.js)
                                                                                                    	at <anonymous> (opt/buildAgent/work/b2fef8360e1bcf3d/formats/json/commonMain/src/kotlinx/serialization/json/internal/Polymorphic.kt:20)
                                                                                                    	at encodeToDynamic_0 (opt/buildAgent/work/b2fef8360e1bcf3d/formats/json/jsMain/src/kotlinx/serialization/json/internal/DynamicEncoders.kt:42)
                                                                                                    	at encodeToDynamic (opt/buildAgent/work/b2fef8360e1bcf3d/formats/json/jsMain/src/kotlinx/serialization/json/Dynamics.kt)
                                                                                                    	at encodeToStringFast (runner/work/zipline/zipline/zipline/src/jsMain/kotlin/app/cash/zipline/internal/jsonJs.kt)
                                                                                                    	at <anonymous> (runner/work/zipline/zipline/zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/CallCodec.kt:56)
                                                                                                    	at <anonymous> (runner/work/zipline/zipline/zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/OutboundCallHandler.kt:99)
                                                                                                    	at <anonymous> (runner/work/zipline/zipline/zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/SuspendCallback.kt)
                                                                                                    	at <anonymous> (zipline-root-zipline.js)
                                                                                                    	at <anonymous> (runner/work/zipline/zipline/zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/InboundService.kt:53)
                                                                                                    	at <anonymous> (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/JobSupport.kt)
                                                                                                    	at <anonymous> (kotlinx.coroutines-kotlinx-coroutines-core-js-ir.js)
                                                                                                    	at notifyCompletion (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/JobSupport.kt:369)
                                                                                                    	at completeStateFinalization (mnt/agent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/JobSupport.kt:325)
                                                                                                        ... and 20 more common stack frames skipped
                                                                                                    	at app.cash.zipline.internal.GuestService$Companion$Adapter$GeneratedOutboundService.runJob(GuestService.kt:23)
                                                                                                    	at app.cash.zipline.internal.CoroutineEventLoop$DelayedJob$run$1.invokeSuspend(CoroutineEventLoop.kt:61)
                                                                                                    	at app.cash.zipline.internal.CoroutineEventLoop$DelayedJob$run$1.invoke(Unknown Source:8)
                                                                                                    	at app.cash.zipline.internal.CoroutineEventLoop$DelayedJob$run$1.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at app.cash.zipline.internal.CoroutineEventLoop$DelayedJob.run(CoroutineEventLoop.kt:58)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

### PR DESCRIPTION
**Pull request by Shabinder**
Shall Fix https://github.com/cashapp/zipline/issues/1163.
 - Ending Serial Name Description on encountering a recursive descriptor.
 - Have added a test class with a sample recursive class description.
 - Rather than using a placeholder, used class's simple descriptor name.

PS:
 - Allowing Edits by Maintainers if needed.

### CODE REVIEW

File: zipline/src/hostTest/kotlin/app/cash/zipline/internal/bridge/SerialNameTest.kt [hunk 1]
```diff
@@ -79,4 +80,26 @@ class SerialNameTest {
...
+    val serialName = serialName(
+      "SomeType",
+      serializers = listOf(
+        serializer<SomeRecursiveType>(),
+      ),
+    )
+    assertEquals(
+      expected = "SomeType<" +
+        "app.cash.zipline.internal.bridge.SomeRecursiveType<" +
+        "app.cash.zipline.internal.bridge.SomeRecursiveType?<app.cash.zipline.internal.bridge.SomeRecursiveType?>" +
```
Comment (JakeWharton) [inline zipline/src/hostTest/kotlin/app/cash/zipline/internal/bridge/SerialNameTest.kt]: I'm wondering if it's necessary to include the second copy here. If we break before recursing it won't be included, and isn't it entirely redundant?

File: zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/ZiplineServiceAdapter.kt [hunk 2]
```diff
@@ -93,7 +93,15 @@ internal fun serialName(typeName: String, serializers: List<KSerializer<*>>): St
...
 
-private fun descriptorName(typeName: SerialDescriptor): String {
+private fun descriptorName(typeName: SerialDescriptor, visited: MutableSet<SerialDescriptor> = mutableSetOf()): String {
+  // Check if we've already visited this descriptor to avoid infinite recursion
+  if (visited.contains(typeName)) {
+    return typeName.serialName
+  }
+
+  // Mark this descriptor as visited
+  visited.add(typeName)
```
Comment (JakeWharton) [inline zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/ZiplineServiceAdapter.kt]:
```suggestion
  if (!visited.add(typeName)) {
    return typeName.serialName
  }
```

File: zipline/src/hostTest/kotlin/app/cash/zipline/internal/bridge/SerialNameTest.kt (hunk 1 above)
Comment (Shabinder) [reply zipline/src/hostTest/kotlin/app/cash/zipline/internal/bridge/SerialNameTest.kt]: @JakeWharton  you are correct, it does exit, in above: 
 1. 1st serialName of **Non-Nullable** `SomeRecursiveType`.
 2. 1st serialName of **Nullable** `SomeRecursiveType`.
 3. 2nd **Recurse** serialName of **Nullable** `SomeRecursiveType`, hence exits with plain serialName of descriptor.

Comment (JakeWharton) [reply zipline/src/hostTest/kotlin/app/cash/zipline/internal/bridge/SerialNameTest.kt]: Right my question was if the second copy is actually necessary or redundant

Comment (Shabinder) [reply zipline/src/hostTest/kotlin/app/cash/zipline/internal/bridge/SerialNameTest.kt]: AhUnderstood what you mean,
Yes we could just return empty string once we hit recursion instead of repeating serialName, shouldn't matter.

Comment (Shabinder) [reply zipline/src/hostTest/kotlin/app/cash/zipline/internal/bridge/SerialNameTest.kt]: @JakeWharton just got back to the project requiring this, pardon for being late, got stuck in other projects.

I have made the change you suggested of removing the second serial name copy and using a self explanatory tag.

lemme know if you need anything from my side for this PR's Scope, would love to get this merged and use the lib, instead of maintaining a fork :-]

Comment (JakeWharton) [reply zipline/src/hostTest/kotlin/app/cash/zipline/internal/bridge/SerialNameTest.kt]: Can you add an entry to the change log in the unreleased section? Then I can get this merged and probably released.

Comment (Shabinder) [reply zipline/src/hostTest/kotlin/app/cash/zipline/internal/bridge/SerialNameTest.kt]: Done ✅

**Review by JakeWharton — APPROVED** [review]
