### PR TITLE
Break the reference cycle between ZiplineScope and its services

### LINKED ISSUE #776: Don’t mix circular references and JS Leak Detection
It looks like it causes instability in QuickJS.

https://github.com/cashapp/zipline/actions/runs/3715807899/jobs/6301407816

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff71fa3b759, pid=15812, tid=15814
#
# JRE version: OpenJDK Runtime Environment Zulu11.60+19-CA (11.0.17+8) (build 11.0.17+8-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu11.60+19-CA (11.0.17+8-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [quickjs2619729428427931323.tmp+0x3b759]  __JS_FreeValueRT+0xa9
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/runner/work/zipline/zipline/zipline/core.15812)
#
# An error report file with more information is saved as:
# /home/runner/work/zipline/zipline/zipline/hs_err_pid15812.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
app.cash.zipline.LeakedServicesTest[jvm] > jsLeaksService[jvm] SKIPPED
```

Can fix by changing the scope to not keep a reference to the outbound service.

### PR DESCRIPTION
**Pull request by swankjesse**
Closes: https://github.com/cashapp/zipline/issues/776

### CODE REVIEW

File: zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/OutboundCallHandler.kt [hunk 1]
```diff
@@ -119,15 +124,15 @@ internal class OutboundCallHandler(
...
-  ) : SuspendCallback<R>, HasPassByReferenceName, ZiplineScoped {
+  private inner class RealSuspendCallback<R>
+    : SuspendCallback<R>, HasPassByReferenceName, ZiplineScoped {
     lateinit var internalCall: InternalCall
     lateinit var externalCall: Call
     lateinit var continuation: Continuation<R>
     var callStart: Any? = null
 
     override var passbyReferenceName: String? = null
+    override val scope: ZiplineScope = this@OutboundCallHandler.scope
```
Comment (JakeWharton) [inline zipline/src/commonMain/kotlin/app/cash/zipline/internal/bridge/OutboundCallHandler.kt]:
```suggestion
    override val scope: ZiplineScope get() = this@OutboundCallHandler.scope
```

**Review by JakeWharton — APPROVED** [review]
