### PR TITLE
Make ZiplineCache resilient to disk write failures

### LINKED ISSUE #1369: Cache needs to be more resilient to a full disk
We’ve seen some crashes where the cache behaves badly when the disk isn’t writable because it’s full.

### PR DESCRIPTION
**Pull request by swankjesse**
This pulls the try/catch block up to the public API of ZiplineCache. Exceptions put the cache in a degraded mode where all reads return null and all writes do nothing. This yields bad caching, but that's our best option given an unwritable disk.

This also introduces a very aggressive test case to confirm that the cache can recover from any write failure.

Closes: https://github.com/cashapp/zipline/issues/1369

### CODE REVIEW

File: zipline-loader/src/commonMain/kotlin/app/cash/zipline/loader/internal/fetcher/FsCachingFetcher.kt [hunk 1]
```diff
@@ -34,9 +34,9 @@ internal class FsCachingFetcher(
     nowEpochMs: Long,
     baseUrl: String?,
     url: String,
-  ): ByteString? {
+  ): ByteString {
     return cache.getOrPut(applicationName, sha256, nowEpochMs) {
-      delegate.fetch(applicationName, eventListener, id, sha256, nowEpochMs, baseUrl, url)
+      delegate.fetch(applicationName, eventListener, id, sha256, nowEpochMs, baseUrl, url)!!
```
Comment (swankjesse) [inline zipline-loader/src/commonMain/kotlin/app/cash/zipline/loader/internal/fetcher/FsCachingFetcher.kt:39]: The concrete implementation of `Delegate` is an HttpFetcher that never returns null. (Though it does throw exceptions).

**Comment by swankjesse** [comment]
CI failure is unrelated but does need a fix!

```

+ yum -y install centos-release-scl
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/x86_64
```

File: zipline-loader/src/commonMain/kotlin/app/cash/zipline/loader/ZiplineCache.kt [hunk 2]
```diff
@@ -80,27 +80,23 @@ class ZiplineCache internal constructor(
...
-  internal fun write(
+  private fun write(
     applicationName: String,
     sha256: ByteString,
     content: ByteString,
     nowEpochMs: Long,
     isManifest: Boolean = false,
     manifestFreshAtMs: Long? = null,
-  ): Files? {
-    try {
```
Comment (swankjesse) [inline zipline-loader/src/commonMain/kotlin/app/cash/zipline/loader/ZiplineCache.kt:91]: lots of the diffs in this file are moving try/catch blocks outside of implementation-detail functions and towards the public API. They’re more coarse-grained that way and that’s okay.

File: zipline-loader/src/commonMain/kotlin/app/cash/zipline/loader/ZiplineCache.kt [hunk 3]
```diff
@@ -121,28 +117,40 @@ class ZiplineCache internal constructor(
...
+    val content = download()
+    try {
+      write(
+        applicationName = applicationName,
+        sha256 = sha256,
+        content = content,
+        isManifest = false,
+        nowEpochMs = nowEpochMs,
+      )
+    } catch (e: Exception) {
```
Comment (swankjesse) [inline zipline-loader/src/commonMain/kotlin/app/cash/zipline/loader/ZiplineCache.kt:141]: Discarded exception is recovered here:
https://github.com/cashapp/zipline/pull/1375

File: zipline-loader/src/commonMain/kotlin/app/cash/zipline/loader/internal/fetcher/FsCachingFetcher.kt (hunk 1 above)
Comment (JakeWharton) [reply zipline-loader/src/commonMain/kotlin/app/cash/zipline/loader/internal/fetcher/FsCachingFetcher.kt:39]: Can we move that invariant up to the property type? Then presumably its covariant override will eliminate the need for this double bang.

File: zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt [hunk 4]
```diff
@@ -0,0 +1,187 @@
...
+ * expects from the cache: it accepts a wide variety of download counts. But regardless of whether
+ * the file system accepts writes, the cache should never return invalid results.
+ */
+class ZiplineCacheFaultsTest {
+  @Test
+  fun openMissHitClose(): Unit = runBlocking {
+    // How many writes are attempted in this test in the happy path. Determined experimentally!
+    val noFailuresWriteCount = 20
+
+    for (i in 0 until noFailuresWriteCount + 1) {
```
Comment (JakeWharton) [inline zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt:40]: until is going to do `- 1`
```suggestion
    for (i in 0..noFailuresWriteCount) {
```

File: zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt [hunk 5]
```diff
@@ -0,0 +1,187 @@
...
+      assertThat(tester.fileSystemWriteCount).isLessThanOrEqualTo(noFailuresWriteCount)
+    }
+  }
+
+  @Test
+  fun openMissClose_OpenHitClose(): Unit = runBlocking {
+    // How many writes are attempted in this test in the happy path. Determined experimentally!
+    val noFailuresWriteCount = 20
+
+    for (i in 0 until noFailuresWriteCount + 1) {
```
Comment (JakeWharton) [inline zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt:69]:
```suggestion
    for (i in 0..noFailuresWriteCount) {
```

File: zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt [hunk 6]
```diff
@@ -0,0 +1,187 @@
...
+      assertThat(tester.fileSystemWriteCount).isLessThanOrEqualTo(noFailuresWriteCount)
+    }
+  }
+
+  @Test
+  fun openFailClose_OpenMissClose_OpenHitClose(): Unit = runBlocking {
+    // How many writes are attempted in this test in the happy path. Determined experimentally!
+    val noFailuresWriteCount = 27
+
+    for (i in 0 until noFailuresWriteCount + 1) {
```
Comment (JakeWharton) [inline zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt:100]:
```suggestion
    for (i in 0..noFailuresWriteCount) {
```

File: zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt [hunk 7]
```diff
@@ -0,0 +1,187 @@
...
+    }
+  }
+
+  /** This test confirms that stale cached results are pruned. */
+  @Test
+  fun openMissClose_openStaleClose(): Unit = runBlocking {
+    // How many writes are attempted in this test in the happy path. Determined experimentally!
+    val noFailuresWriteCount = 31
+
+    for (i in 0 until noFailuresWriteCount + 1) {
```
Comment (JakeWharton) [inline zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt:139]:
```suggestion
    for (i in 0..noFailuresWriteCount) {
```

File: zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt [hunk 8]
```diff
@@ -0,0 +1,187 @@
...
+        assertThat(tester.downloadCount).isEqualTo(2)
+
+        // The subsequent launch should have between 2 and 4 cache misses, depending on what was
+        // successfully written to the cache last time.
+        loadApp()
+        assertThat(tester.downloadCount).isLessThanOrEqualTo(4)
+      }
+
+      // Assert more strictly if we didn't need to inject any write failures.
+      if (i >= noFailuresWriteCount) {
```
Comment (JakeWharton) [inline zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt:56]: Not that it matters, but this should never be able to be greater than, right? It could only ever be equal to.

**Review by JakeWharton — APPROVED** [review]

File: zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt (hunk 4 above)
Comment (JakeWharton) [reply zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt:40]: Got 'em in the follow-up.

File: zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt (hunk 8 above)
Comment (swankjesse) [reply zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt:56]: ooooh yeah lemme fix that.

Comment (swankjesse) [reply zipline-loader/src/commonTest/kotlin/app/cash/zipline/loader/internal/cache/ZiplineCacheFaultsTest.kt:56]: https://github.com/cashapp/zipline/pull/1375

File: zipline-loader/src/commonMain/kotlin/app/cash/zipline/loader/internal/fetcher/FsCachingFetcher.kt (hunk 1 above)
Comment (swankjesse) [reply zipline-loader/src/commonMain/kotlin/app/cash/zipline/loader/internal/fetcher/FsCachingFetcher.kt:39]: https://github.com/cashapp/zipline/pull/1375
