### PR TITLE
Fix collision in serviceTypeCache keys

### LINKED ISSUE #1039: ServiceTypeCache keys not distinct
I saw some ClassCastExceptions internal to Zipline and investigated. We were attempting to serialize one type (`Foo`) with a serializer of another type (`Bar`). What the two types have in common is the application has a `Flow<Foo>` in one place, and a `Flow<Bar>` in another.

When inspecting the cache keys used for these, I would expect fully-qualified type names:
 * `app.cash.zipline.internal.bridge.FlowZiplineCollector<com.example.Foo>`
 * `app.cash.zipline.internal.bridge.FlowZiplineCollector<com.example.Bar>`

Instead, the generic types were omitted:
 * `app.cash.zipline.internal.bridge.FlowZiplineCollector<T>`

A good fix for this won’t reduce the hit rate of the cache.

### PR DESCRIPTION
**Pull request by swankjesse**
We were selecting cache keys at build-time, which resulted in multiple flows using the same serializer instances, despite having different runtime types.

This changes key construction to happen at runtime instead.

Closes: https://github.com/cashapp/zipline/issues/1039

### CODE REVIEW

File: zipline/src/hostTest/kotlin/app/cash/zipline/FlowTest.kt [hunk 1]
```diff
@@ -241,4 +244,28 @@ internal class FlowTest {
     assertEquals(setOf(), endpointA.serviceNames)
     assertEquals(setOf(), endpointB.serviceNames)
   }
+
+  /** https://github.com/cashapp/zipline/issues/1039 */
```
Comment (swankjesse) [inline zipline/src/hostTest/kotlin/app/cash/zipline/FlowTest.kt:248]: This test crashed on the old code attempting to use an Int serializer on a string.

**Review by JakeWharton — APPROVED** [review]
